name: Deploy-Worker

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main-worker, homologacao-worker ]
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
  # pull_request:
  #   branches: [ main-worker, homologacao-worker ]
  #   paths-ignore:
  #     - README.md
  #     - .vscode/**
  #     - .gitignore
      
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  producao:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main-worker' }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}           
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./SCAE.WorkerService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/scae-worker:latest, ${{ secrets.DOCKERHUB_USERNAME }}/scae-worker:${{ github.run_number }}
  homologacao:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'homologacao-worker' }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}           
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./SCAE.WorkerService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/scae-worker-hml:latest, ${{ secrets.DOCKERHUB_USERNAME }}/scae-worker-hml:${{ github.run_number }}
